site_name: Arrlio
nav:
  - About: index.md
  - Installation: installation.md
  - User Guide:
    - Basic: user_guide/basic.md
    - Task arguments: user_guide/task_args.md
    - Task result: user_guide/task_result.md
    - Settings: user_guide/settings.md
    - Backends: user_guide/backends.md
    - Advanced:
      - Backend configuration: user_guide/advanced/backend_configuration.md
      - Task submitting: user_guide/advanced/task_submitting.md
      - Generators: user_guide/advanced/generators.md
  - API Reference: api_reference.md
theme:
  name: material
  palette:
    primary: teal
    accent: light blue
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - admonition
plugins:
  - search
  - mkdocstrings
repo_url: https://github.com/levsh/arrlio
