site_name: Arrlio

nav:
  - About: index.md
  - Installation: installation.md
  - User Guide:
    - Basic: user_guide/basic.md
    - Task arguments: user_guide/task_args.md
    - Task result: user_guide/task_result.md
    - Settings: user_guide/settings.md
    - Brokers: user_guide/brokers.md
    - Result backends: user_guide/result_backends.md
    - Event backends: user_guide/event_backends.md
    - Advanced:
      - Configuration: user_guide/advanced/configuration.md
      - Task submitting: user_guide/advanced/task_submitting.md
      - Generators: user_guide/advanced/generators.md
  - API Reference: api_reference.md

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: light blue
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - admonition

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: list
            separate_signature: true
            line_length: 60

extra_css:
  - css/extra.css

repo_url: https://github.com/levsh/arrlio
