# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Pull Docker images
      run: |
        docker pull rabbitmq:3-management
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install -d
    - name: Run linters
      run: |
        pipenv run inv run-linters
    - name: Run test
      run: |
        pipenv run inv run-tests
    - name: Generate shields.io coverage
      run: |
        pipenv run inv generate-coverage-gist
    - name: Update coverage badge Gist
      run: |
        curl \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GIST_PAT }}" \
          https://api.github.com/gists/727ed723ccaee0d5825513af6472e3a5 \
          -d @artifacts/shields_io_coverage_gist_data.json
